client:
  build: .
  container_name: sensu
  restart: unless-stopped
  command: client
  hostname: master
  volumes:
   - /dev:/host_dev/:ro
   - /proc:/host_proc/:ro
   - /sys:/host_sys/:ro
   - ./conf.d:/etc/sensu/conf.d
  environment:
    CLIENT_NAME:  master
    CLIENT_ADDRESS: 10.82.76.14
    CLIENT_SUBSCRIPTIONS: all,default
    RABBITMQ_HOST: 200.131.6.6
    RABBITMQ_PORT: 5672
    HOST_DEV_DIR: /host_dev
    HOST_PROC_DIR: /host_proc
    HOST_SYS_DIR: /host_sys

