api:
  image: sstarcher/sensu:0.23.2
  restart: unless-stopped
  command: api
  links:
    - rabbitmq
    - redis
  volumes:
    - ./check.d:/etc/sensu/check.d
  environment:
    RABBITMQ_PORT: 5672
server:
  image: sstarcher/sensu:0.23.2
  restart: unless-stopped
  command: server
  links:
    - rabbitmq
    - redis
    - api
    - influxdb
  volumes:
    - ./conf.d:/etc/sensu/conf.d
    - ./check.d:/etc/sensu/check.d
    - ./handlers:/etc/sensu/handlers
    - ./extensions:/etc/sensu/extensions
    - ./plugins:/etc/sensu/plugins
  environment:
    RABBITMQ_PORT: 5672
    RUNTIME_INSTALL: snmp
client:
  build: .
  restart: unless-stopped
  command: client
  hostname: CoreOs
  volumes:
   - /dev:/host_dev/:ro
   - /proc:/host_proc/:ro
   - /sys:/host_sys/:ro
   - ./conf.d:/etc/sensu/conf.d
  environment:
    CLIENT_NAME: CoreOs
    CLIENT_ADDRESS: 10.0.0.1
    CLIENT_SUBSCRIPTIONS: default, snmp
    RABBITMQ_HOST: 10.0.0.1
    RABBITMQ_PORT: 5672
    HOST_DEV_DIR: /host_dev
    HOST_PROC_DIR: /host_proc
    HOST_SYS_DIR: /host_sys
uchiwa:
  image: sstarcher/uchiwa:0.15.0
  restart: unless-stopped
  links:
    - api:sensu
  ports:
    - '80:3000'
  volumes:
    - ./uchiwa/uchiwa.json:/etc/sensu/uchiwa.json
rabbitmq:
  image: rabbitmq:3.6-management
  restart: unless-stopped
  ports:
    - '5672:5672'
    - '15672:15672'
redis:
  image: redis
  restart: unless-stopped
  volumes:
    - /srv/redis:/data
influxdb:
  image: tutum/influxdb:0.9 
  restart: unless-stopped
  volumes:
    - /srv/influxdb:/data
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8089:8089/udp"
    - "2003:2003"
  environment:
    PRE_CREATE_DB: sensu
    UDP_DB: sensu
    UDP_PORT: 8089
    COLLECTD_DB: collectd
    GRAPHITE_DB: jvm
grafana:
  image: grafana/grafana:2.6.0
  restart: unless-stopped
  volumes:
   -  /srv/grafana:/var/lib/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
collectd:
  build: ../collectd
  restart: unless-stopped
  volumes:
    - ../collectd/conf.d:/etc/collectd/collectd.conf.d
    - /srv/collectd:/var/lib/collectd
  links:
    - influxdb
