api:
  image: sstarcher/sensu
  command: api
  links:
    - rabbitmq
    - redis
  volumes:
    - ./check.d:/etc/sensu/check.d
  environment:
    RABBITMQ_PORT: 5672
server:
  image: sstarcher/sensu
  command: server
  links:
    - rabbitmq
    - redis
    - api
  volumes:
    - ./conf.d:/etc/sensu/conf.d
    - ./check.d:/etc/sensu/check.d
    - ./handlers:/etc/sensu/handlers
    - ./extensions:/etc/sensu/extensions
    - ./plugins:/etc/sensu/plugins
  environment:
    RABBITMQ_PORT: 5672
client:
  image: guimaluf/sensu
  command: client
  hostname: CoreOs
  volumes:
   - /dev:/host_dev/:ro
   - /proc:/host_proc/:ro
   - /sys:/host_sys/:ro
   - ./handlers:/etc/sensu/handlers
  environment:
    CLIENT_NAME: CoreOs
    CLIENT_ADDRESS: 10.0.0.1
    CLIENT_SUBSCRIPTIONS: all,default
    RABBITMQ_HOST: 10.0.0.1
    RABBITMQ_PORT: 5672
    HOST_DEV_DIR: /host_dev
    HOST_PROC_DIR: /host_proc
    HOST_SYS_DIR: /host_sys
uchiwa:
  image: sstarcher/uchiwa
  links:
    - api:sensu
  ports:
    - '80:3000'
rabbitmq:
  image: rabbitmq:3.5-management
  ports:
    - '5672:5672'
redis:
  image: redis
  volumes:
    - /srv/redis:/data
influxdb:
  image: tutum/influxdb:latest
  volumes:
    - /srv/influxdb:/data
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8089:8089/udp"
  environment:
    PRE_CREATE_DB: sensu
    UDP_DB: sensu
    UDP_PORT: 8089
    COLLECTD_DB: collectd
grafana:
  image: grafana/grafana:2.6.0
  ports:
    - "3000:3000"
  links:
    - influxdb
collectd:
  build: ../collectd
  volumes:
    - ../collectd/conf.d:/etc/collectd/collectd.conf.d
    - /srv/collectd:/var/lib/collectd
  links:
    - influxdb
